version: '3.4'

services:

  #  seq:
  #    image: datalust/seq:latest

  sqldata:
    image: mysql:8.0

  redisdata:
    image: redis:alpine

  #  grafana:
  #    image: "grafana/grafana"
  #
  #  prom:
  #    image: "prom/prometheus"

  rabbitmq:
    image: rabbitmq:3-management-alpine

  stream-srs:
    image: chuongtran1999dn/team5-srs:latest
  
  #  web-status:
  #    image: ${REGISTRY:-team5}/web-status:${PLATFORM:-linux}-${TAG:-latest}
  #    build:
  #      context: .
  #      dockerfile: WebApps/WebStatus/Dockerfile

  team5apigw:
    image: envoyproxy/envoy:v1.14.1

